In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
import registration as rg

In [5]:
templateImagePath = "CCF_DATA/average_template_25.nii.gz"
dataImagePath = "../registration/B39/brain_25.nii.gz"
annotationImagePath = "CCF_DATA/annotation_25.nii.gz"

In [7]:
import os
outputDir = "reg"
if not os.path.isdir(outputDir):
    os.mkdir(outputDir)
    
if not os.path.isdir("reg/tests"):
    os.mkdir("reg/tests")

In [20]:
fixedImagePath = templateImagePath
movingImagePath = dataImagePath

In [16]:
from reconstruction import create_nifti_image

In [17]:
A, axisAlignedData = rg.axisAlignData(fixedImagePath, movingImagPath)

axisAlignedDataPath  = os.path.join(outputDir , "axisAlignedData.nii.gz")
create_nifti_image(axisAlignedData, 25, axisAlignedDataPath, 1)

100%|███████████████████████████████████████████████████████████████████████████████| 528/528 [00:02<00:00, 241.21it/s]


In [21]:
movingImagePath = axisAlignedDataPath

In [24]:
elastixResult  = rg.elastixRegistration(fixedImagePath , movingImagePath, outputDir, rescale=True)

AttributeError: module 'registration' has no attribute 'elastixTransformation'

In [26]:
elastixResult  = rg.elastixTransformation(axisAlignedDataPath, outputDir)

In [27]:
movingImagePath = elastixResult

In [28]:
deformationField  = rg.sliceToSlice3DLaplacian(fixedImagePath , movingImagePath , axis =0 )


 81%|█████████████████████████████████████████████████████████████████▏              | 430/528 [09:06<01:53,  1.16s/it]C:\Users\3i\anaconda3\envs\tissuecyte\lib\site-packages\numpy\lib\function_base.py:4573: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
100%|████████████████████████████████████████████████████████████████████████████████| 528/528 [10:50<00:00,  1.23s/it]


Building data for Laplacian Sparse Matrix A
Creating Laplacian Sparse Matrix A
dx calculated in 342.9300584793091s
dz calculated in 643.5535998344421s


NameError: name 'np' is not defined

In [29]:
import numpy as np

In [31]:
np.save(os.path.join(outputDir,"deformation3d.npy"), deformationField)
transformedData   = rg.applyDeformationField(movingImagePath , deformationField)
refinedResultPath = os.path.join(outputDir, "elastixRefined.nii.gz")
create_nifti_image(transformedData, 2.5, refinedResultPath, 1/2)

In [32]:
print(A)

[[ 9.99997081e-01 -5.16963473e-04 -2.36031453e-03  7.76355103e-01]
 [ 3.86390408e-04  9.98486871e-01 -5.49892649e-02  1.57277509e+01]
 [ 2.38517051e-03  5.49881924e-02  9.98484156e-01 -1.18953976e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
